name: DAST

on:
  workflow_dispatch:
  # push: # Any branch
  # pull_request:
  #   branches:
  #     - main

jobs:
  zap_scan:
    name: ZAP Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - Web
          - PublicAPI
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start the Application
        run: |
          docker build --pull -t web -f src/Web/Dockerfile .
          docker build --pull -t publicapi -f src/PublicAPI/Dockerfile .
          docker run --name eshopweb --rm -d -p 5106:5106 web
          docker run --name eshoppublicapi --rm -d -p 5200:5200 publicapi

      - name: Set target URL
        run: |
          if [[ "${{ matrix.image }}" == "Web" ]]; then
            echo "TARGET=http://localhost:5106" >> $GITHUB_ENV
          else
            echo "TARGET=http://localhost:5200" >> $GITHUB_ENV
          fi

      - name: ZAP Scan ${{ matrix.image }}
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: ${{ env.TARGET }}
          allow_issue_writing: false # Skip creating issue for now
          # token: ${{ secrets.GITHUB_TOKEN }}
          # docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a'

      - name: Upload ZAP Report for ${{ matrix.image }}
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-${{ matrix.image }}
          path: zap_scan