name: Dotnet Core

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Read solution path from JSON
      id: read_config
      run: |
        SOLUTION_PATH=$(jq -r '.solution_path[]' solutions.json)
        echo "Read solution_path: $SOLUTION_PATH"
        echo "SOLUTION_PATH=$SOLUTION_PATH" >> $GITHUB_ENV

    - name: Build with dotnet
      run: dotnet build $SOLUTION_PATH --configuration Release

    - name: Test with dotnet
      run: dotnet test $SOLUTION_PATH --configuration Release
